models/Identity.php
<?php

namespace app\models;

use app\application\entities\User;
use app\application\repositories\UserRepository;
use yii\web\IdentityInterface;

class Identity implements IdentityInterface
{
    private $user;

    public function __construct(User $user)
    {
        $this->user = $user;
    }

    /**
     * @param int $id
     *
     * @return Identity|null
     */
    public static function findIdentity($id)
    {
        $user = self::getRepository()->find($id);

        return $user ? new self($user) : null;
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->user->id;
    }

    public function getAuthKey(): string
    {
        return $this->user->auth_key;
    }

    public function validateAuthKey($authKey): bool
    {
        return $this->getAuthKey() === $authKey;
    }

    public function getUsername()
    {
        return $this->user->username;
    }

    public function getBalance()
    {
        return $this->user->balance;
    }

    /**
     * @inheritDoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {

    }


    /**
     * @return UserRepository
     */
    private static function getRepository(): UserRepository
    {
        return \Yii::$container->get(UserRepository::class);
    }
}

controllers/AuthController.php
<?php

namespace app\controllers;


use app\application\forms\SignupLoginForm;
use app\application\services\auth\SignupService;
use app\application\services\auth\UserAlreadyExistsException;
use app\models\Identity;
use Yii;
use yii\base\Module;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;

class AuthController extends Controller
{
    /**
     * @var SignupService
     */
    private $signup;

    /**
     * AuthController constructor.
     *
     * @param string        $id
     * @param Module        $module
     * @param SignupService $signup
     * @param array         $config
     */
    public function __construct($id, Module $module, SignupService $signup, array $config = [])
    {
        parent::__construct($id, $module, $config);
        $this->signup = $signup;
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only'  => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow'   => true,
                        'roles'   => ['@'],
                    ],
                ],
            ],
            'verbs'  => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }


    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $form = new SignupLoginForm();

        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            try {
                $user = $this->signup->signup($form);
            } catch (UserAlreadyExistsException $exception) {
                $user = $exception->getUser();
            } catch (\Exception $exception) {
                Yii::$app->errorHandler->logException($exception);

                return $this->refresh();
            }
            Yii::$app->user->login(
                new Identity($user),
                $form->rememberMe ? Yii::$app->params['user.rememberMe'] : 0
            );

            return $this->goBack();
        }

        return $this->render(
            'login',
            [
                'model' => $form,
            ]
        );
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

controllers/PaymentController.php
<?php

namespace app\controllers;


use app\application\entities\TransferException;
use app\application\forms\PaymentHistorySearch;
use app\application\forms\TransferForm;
use app\application\helpers\MoneyHelper;
use app\application\repositories\UserRepository;
use app\application\services\payment\PaymentService;
use Yii;
use yii\base\Module;
use yii\filters\AccessControl;
use yii\helpers\Html;
use yii\web\Controller;

class PaymentController extends Controller
{
    public $defaultAction = 'history';
    /**
     * @var PaymentService
     */
    private $paymentService;
    /**
     * @var UserRepository
     */
    private $userRepository;

    /**
     * PaymentController constructor.
     *
     * @param string         $id
     * @param Module         $module
     * @param PaymentService $paymentService
     * @param UserRepository $userRepository
     * @param array          $config
     */
    public function __construct(
        $id,
        Module $module,
        PaymentService $paymentService,
        UserRepository $userRepository,
        array $config = []
    ) {
        parent::__construct($id, $module, $config);
        $this->paymentService = $paymentService;
        $this->userRepository = $userRepository;
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }


    public function actionTransfer()
    {
        $form = new TransferForm();

        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            try {
                $this->paymentService->transfer(
                    Yii::$app->user->getIdentity()->getUsername(),
                    $form->username,
                    MoneyHelper::balanceForEntity($form->transfer_amount)
                );
                Yii::$app->session->setFlash(
                    'success',
                    Yii::$app->formatter->asCurrency(
                        Html::encode($form->transfer_amount)
                    ).' was successfully transferred to '.Html::encode($form->username).'.'
                );
            } catch (TransferException $exception) {
                Yii::$app->session->setFlash('error', Html::encode($exception->getMessage()));

                return $this->refresh();
            } catch (\Exception $exception) {
                Yii::$app->errorHandler->logException($exception);
                throw $exception;
            }

            return $this->goHome();
        }

        return $this->render(
            'transfer',
            [
                'model' => $form,
            ]
        );
    }

    public function actionHistory()
    {
        $searchModel = new PaymentHistorySearch();
        $dataProvider = $searchModel->search(
            Yii::$app->request->queryParams,
            Yii::$app->user->id
        );

        return $this->render(
            'history',
            [
                'searchModel'  => $searchModel,
                'dataProvider' => $dataProvider,
            ]
        );
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use yii\web\Controller;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
}

controllers/UsersController.php
<?php

namespace app\controllers;


use app\application\forms\UserSearch;
use yii\web\Controller;

class UsersController extends Controller
{
    public $defaultAction = 'list';

    public function actionList()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(\Yii::$app->request->queryParams);

        return $this->render(
            'list',
            [
                'searchModel'  => $searchModel,
                'dataProvider' => $dataProvider,
            ]
        );
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use app\application\helpers\MoneyHelper;
use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\helpers\Html;
use yii\widgets\Breadcrumbs;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin(
        [
            'brandLabel' => 'Demo project',
            'brandUrl'   => Yii::$app->homeUrl,
            'options'    => [
                'class' => 'navbar-inverse navbar-fixed-top',
            ],
        ]
    );
    if (Yii::$app->user->isGuest) {
        $items[] = ['label' => 'Login', 'url' => ['/auth/login']];
    } else {
        $items[] = ['label' => 'Transfer funds', 'url' => ['/payment/transfer']];
        $items[] = [
            'label' => 'Balance: '.Html::encode(
                    Yii::$app->formatter->asCurrency(
                        MoneyHelper::balanceForHumans(
                            Yii::$app->user->getIdentity()->getBalance()
                        )
                    )
                ),
            'url'   => ['/payment/history'],
        ];
        $items[] = '<li>'
            .Html::beginForm(['/auth/logout'], 'post')
            .Html::submitButton(
                'Logout ('.Html::encode(Yii::$app->user->identity->getUsername()).')',
                ['class' => 'btn btn-link logout']
            )
            .Html::endForm()
            .'</li>';
    }
    echo Nav::widget(
        [
            'options' => ['class' => 'navbar-nav navbar-right'],
            'items'   => $items,
        ]
    );
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget(
            [
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]
        ) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Krajcik <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/payment/history.php
<?php

use app\application\entities\PaymentHistory;
use app\application\helpers\MoneyHelper;
use kartik\date\DatePicker;
use yii\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel \app\application\forms\PaymentHistorySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
$this->title = 'Payment history';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="payment-history">
    <?= GridView::widget(
        [
            'dataProvider' => $dataProvider,
            'filterModel'  => $searchModel,
            'rowOptions'   => function (PaymentHistory $model) use ($searchModel) {
                $c = $searchModel->getSelfId() == $model->from
                    ? 'info' : 'success';

                return ['class' => $c];
            },
            'columns'      => [
                [
                    'label'     => 'Direction of payment',
                    'attribute' => 'status',
                    'filter'    => MoneyHelper::getPaymentDirectionList(),
                    'value'     => function (PaymentHistory $model) use ($searchModel) {
                        return $searchModel->getSelfId() == $model->from ?
                            'Sent to' : 'Received from';
                    },

                    'format' => 'html',
                ],
                [
                    'label'     => 'Username',
                    'attribute' => 'username',
                    'value'     => function (PaymentHistory $model) use ($searchModel) {
                        return $searchModel->getSelfId() == $model->from ?
                            Html::encode($model->receiver->username) : Html::encode($model->sender->username);
                    },

                    'format' => 'html',
                ],
                [
                    'label'     => 'Date time',
                    'attribute' => 'created_at',
                    'filter'    => DatePicker::widget(
                        [
                            'model'         => $searchModel,
                            'attribute'     => 'date_from',
                            'attribute2'    => 'date_to',
                            'type'          => DatePicker::TYPE_RANGE,
                            'separator'     => '-',
                            'pluginOptions' => [
                                'todayHighlight' => true,
                                'autoclose'      => true,
                                'format'         => 'yyyy-mm-dd',
                            ],
                        ]
                    ),
                    'format'    => 'datetime',
                ],
                [
                    'attribute' => 'transfer_amount',
                    'value'     => function (PaymentHistory $model) {
                        return MoneyHelper::balanceForHumans($model->transfer_amount);
                    },
                    'format'    => 'currency',
                ],
            ],
        ]
    ); ?>
</div>

views/payment/transfer.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model \app\application\forms\TransferForm */

use kartik\money\MaskMoney;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$this->title = 'Transfer funds to another user';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="payment-transfer">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields:</p>

    <?php $form = ActiveForm::begin(
        [
            'id'     => 'transfer-form',
            'layout' => 'horizontal',
        ]
    ); ?>

    <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

    <?= $form->field($model, 'transfer_amount')->widget(
        MaskMoney::class,
        [
            'pluginOptions' => [
                'prefix'           => '$ ',
                'allowNegative'    => false,
                'displayInputName' => false,
            ],
        ]
    ); ?>

    <div class="form-group">
        <div class="col-lg-offset-3 col-lg-11">
            <?= Html::submitButton('Transfer funds', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/users/list.php
<?php

use app\application\entities\User;
use app\application\helpers\MoneyHelper;
use kartik\date\DatePicker;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel \app\application\forms\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
$this->title = 'Users';
?>
<div class="user-index">
    <?= GridView::widget(
        [
            'dataProvider' => $dataProvider,
            'filterModel'  => $searchModel,
            'columns'      => [
                'username',
                [
                    'label'     => 'Signup date time',
                    'attribute' => 'created_at',
                    'filter'    => DatePicker::widget(
                        [
                            'model'         => $searchModel,
                            'attribute'     => 'date_from',
                            'attribute2'    => 'date_to',
                            'type'          => DatePicker::TYPE_RANGE,
                            'separator'     => '-',
                            'pluginOptions' => [
                                'todayHighlight' => true,
                                'autoclose'      => true,
                                'format'         => 'yyyy-mm-dd',
                            ],
                        ]
                    ),
                    'format'    => 'datetime',
                ],
                [
                    'attribute' => 'balance',
                    'value'     => function (User $model) {
                        return MoneyHelper::balanceForHumans($model->balance);
                    },
                    'format'    => 'currency',
                ],
            ],
        ]
    ); ?>
</div>